# Generated by Django 5.1.15 on 2026-09-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=4, max_digits=18)),
                ("open_price", models.DecimalField(decimal_places=4, max_digits=18)),
                ("high_price", models.DecimalField(decimal_places=4, max_digits=18)),
                ("low_price", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "previous_close",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("change_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("change_percent", models.DecimalField(decimal_places=4, max_digits=8)),
                ("volume", models.BigIntegerField(default=0)),
                ("price_timestamp", models.DateTimeField(db_index=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="instruments.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "market_prices",
                "ordering": ["-price_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["instrument", "-price_timestamp"],
                        name="market_pric_instrum_a8bf45_idx",
                    )
                ],
            },
        ),
    ]
