# Generated by Django 5.1.15 on 2026-09-21 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("DRAWDOWN", "Portfolio Drawdown"),
                            ("CONCENTRATION", "Position Weight Concentration"),
                            ("DAILY_LOSS", "Daily Loss Breach"),
                            ("VOLATILITY", "Volatility Threshold"),
                            ("OPTION_EXPIRY", "Option Expiry Horizon"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "comparator",
                    models.CharField(
                        choices=[
                            ("GT", "Greater Than"),
                            ("LT", "Less Than"),
                            ("GTE", "Greater Than or Equal"),
                            ("LTE", "Less Than or Equal"),
                        ],
                        default="GT",
                        max_length=10,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="portfolios.portfolio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alert_rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "triggered_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("message", models.TextField()),
                ("is_acknowledged", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "db_table": "alert_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["user", "is_active"], name="alert_rules_user_id_362e53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["portfolio", "is_active"], name="alert_rules_portfol_22a9e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["rule", "-created_at"], name="alert_event_rule_id_ddabb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["is_acknowledged", "-created_at"],
                name="alert_event_is_ackn_5d44e0_idx",
            ),
        ),
    ]
