# Generated by Django 5.1.15 on 2026-09-21 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "sectors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("EQUITY", "Equity"),
                            ("ETF", "Exchange Traded Fund"),
                            ("OPTION", "Options Contract"),
                            ("CRYPTO", "Cryptocurrency"),
                            ("CASH", "Cash Equivalent"),
                        ],
                        db_index=True,
                        default="EQUITY",
                        max_length=20,
                    ),
                ),
                ("exchange", models.CharField(default="NSE", max_length=30)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee (₹)"),
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instruments",
                        to="instruments.sector",
                    ),
                ),
            ],
            options={
                "db_table": "instruments",
                "ordering": ["symbol"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "is_active"],
                        name="instruments_symbol_ad0c89_idx",
                    ),
                    models.Index(
                        fields=["asset_class", "is_active"],
                        name="instruments_asset_c_b48a0e_idx",
                    ),
                ],
            },
        ),
    ]
