# Generated by Django 5.1.15 on 2026-09-21 10:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
        ("options", "0001_initial"),
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("DIVIDEND", "Dividend"),
                            ("BONUS", "Bonus Shares"),
                            ("SPLIT", "Stock Split"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("executed_at", models.DateTimeField(db_index=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="instruments.instrument",
                    ),
                ),
                (
                    "option_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="options.optioncontract",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-executed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "-executed_at"],
                        name="transaction_portfol_d90652_idx",
                    ),
                    models.Index(
                        fields=["instrument", "-executed_at"],
                        name="transaction_instrum_c119b1_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="transaction_transac_ddda52_idx",
                    ),
                ],
            },
        ),
    ]
