# Generated by Django 5.1.15 on 2026-09-21 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskMetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("calculation_date", models.DateField(db_index=True)),
                (
                    "volatility_annualized",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("sharpe_ratio", models.DecimalField(decimal_places=4, max_digits=10)),
                ("beta", models.DecimalField(decimal_places=4, max_digits=10)),
                ("max_drawdown", models.DecimalField(decimal_places=4, max_digits=10)),
                ("var_95_daily", models.DecimalField(decimal_places=4, max_digits=18)),
                ("var_99_daily", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "concentration_herfindahl",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("sector_exposure", models.JSONField(default=dict)),
                ("asset_exposure", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_snapshots",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "risk_metric_snapshots",
                "ordering": ["-calculation_date"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "-calculation_date"],
                        name="risk_metric_portfol_67ba52_idx",
                    )
                ],
                "unique_together": {("portfolio", "calculation_date")},
            },
        ),
    ]
