# Generated by Django 5.1.15 on 2026-09-21 10:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
        ("options", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee (₹)"),
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("total_equity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("cash_balance", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "invested_capital",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("realized_pnl", models.DecimalField(decimal_places=4, max_digits=18)),
                ("day_pnl", models.DecimalField(decimal_places=4, max_digits=18)),
                ("day_return_pct", models.DecimalField(decimal_places=4, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "average_buy_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "total_invested",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="instruments.instrument",
                    ),
                ),
                (
                    "option_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="options.optioncontract",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "positions",
            },
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["user", "-created_at"], name="portfolios_user_id_c744e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliosnapshot",
            index=models.Index(
                fields=["portfolio", "-snapshot_date"],
                name="portfolio_s_portfol_4f5098_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfoliosnapshot",
            unique_together={("portfolio", "snapshot_date")},
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["portfolio", "instrument"], name="positions_portfol_cfcf47_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                condition=models.Q(("option_contract__isnull", True)),
                fields=("portfolio", "instrument"),
                name="unique_equity_position_per_portfolio",
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                condition=models.Q(("option_contract__isnull", False)),
                fields=("portfolio", "instrument", "option_contract"),
                name="unique_option_position_per_portfolio",
            ),
        ),
    ]
