# Generated by Django 5.1.15 on 2026-09-21 10:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[("CALL", "Call"), ("PUT", "Put")], max_length=4
                    ),
                ),
                ("strike_price", models.DecimalField(decimal_places=4, max_digits=18)),
                ("expiration_date", models.DateField(db_index=True)),
                ("contract_multiplier", models.PositiveIntegerField(default=100)),
                (
                    "style",
                    models.CharField(
                        choices=[("AMERICAN", "American"), ("EUROPEAN", "European")],
                        default="EUROPEAN",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "underlying",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_contracts",
                        to="instruments.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "option_contracts",
                "ordering": ["expiration_date", "strike_price"],
                "unique_together": {
                    ("underlying", "option_type", "strike_price", "expiration_date")
                },
            },
        ),
    ]
